### ISSUE TITLE
bower module

### ISSUE THREAD

**Issue by marklabenski** [darsain/fpsmeter#11]
Thank you for this great project. 
Browsing the history I've found commits like `Moving away from bower`. Why did you do that?
I just wanted to include this project over bower as any of my other modules. Would you mind if I contribute a bower.json? I somehow never found one in the repo even though you're referencing it inside of commit messages.

**Comment by darsain** [comment]
The reasoning for moving away from bower is here: https://github.com/darsain/fpsmeter/issues/4#issuecomment-31637337

I'm not planning on including `bower.json` again.

**Comment by marklabenski** [comment]
Okay... so you're using a deprecated package manager instead of a widely used one only because you experienced problems some day in the past? That's the reason to not add a simple .json file to support your project for many users? I don't think your project will be worse with an bower.json in it...

**Comment by darsain** [comment]
I'm actually using [duo](https://github.com/duojs/duo), which is a successor to component. That comment was written before duo came out and component became deprecated.

You can consume this library with either duo, or webpack.

**Comment by outofambit** [comment]
you can always do `bower install https://github.com/darsain/fpsmeter.git`

**Comment by marklabenski** [comment]
@outofambit Thank you for this tip.
The thing is, we would have needed the informations in the bower.json file (distributed js file) for automated build processes using wiredep.
I still didn't get the point where the problem is with adding a single json file to the repository..
